version: '3'
services:
  moodle:
    build:
      context: http://github.com/Glutamat42/moodle-docker.git
      args:
        PLUGIN_VERSION: main
        MOODLE_VERSION: 4.2
    ports:
      - 8085:8080
    environment:
      MOODLE_DATABASE_HOST: db_moodle
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_USER: ${_DB_MOODLE_USER}
      MOODLE_DATABASE_PASSWORD: ${_DB_MOODLE_PW}
      MOODLE_DATABASE_NAME: ${_DB_MOODLE_NAME}
      MOODLE_USERNAME: ${_MOODLE_USER}
      MOODLE_PASSWORD: ${_MOODLE_PW}
      MOODLE_HOST: ${_URL_MOODLE}
      PHP_POST_MAX_SIZE: 2048M
      PHP_UPLOAD_MAX_FILESIZE: 2048M
      USER_NAME: student,manager
      USER_PASSWORD: Student1234!1234,Manager1234!1234
      USER_ROLE: false,manager
    volumes:
      - moodle_moodle:/bitnami/moodle
      - moodle_moodledata:/bitnami/moodledata
    depends_on:
      - db_moodle
    restart: unless-stopped

  db_moodle:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      MARIADB_USER: ${_DB_MOODLE_USER}
      MARIADB_PASSWORD: ${_DB_MOODLE_PW}
      MARIADB_ROOT_PASSWORD: ${_DB_ROOT_PW}
      MARIADB_DATABASE: ${_DB_MOODLE_NAME}
      MARIADB_CHARACTER_SET: utf8mb4
      MARIADB_COLLATE: utf8mb4_unicode_ci
    volumes:
      - db_moodle_data:/bitnami/mariadb
    restart: unless-stopped

  db_backend:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      MARIADB_USER: ${_DB_BACKEND_USER}
      MARIADB_PASSWORD: ${_DB_BACKEND_PW}
      MARIADB_ROOT_PASSWORD: ${_DB_ROOT_PW}
      MARIADB_DATABASE: ${_DB_BACKEND_NAME}
      MARIADB_CHARACTER_SET: utf8mb4
      MARIADB_COLLATE: utf8mb4_unicode_ci
    volumes:
      - db_backend_data:/bitnami/mariadb
    restart: unless-stopped

  backend:
    image: ghcr.io/projektadler/adlerbackend:main
    ports:
      - 8086:80
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_DBUSER: ${_DB_BACKEND_USER}
      ASPNETCORE_DBPASSWORD: ${_DB_BACKEND_PW}
      ASPNETCORE_DBNAME: ${_DB_BACKEND_NAME}
      ASPNETCORE_DBHOST: db_backend
      ASPNETCORE_DBPORT: 3306
      ASPNETCORE_ADLER_MOODLEURL: http://${_URL_MOODLE}
      ASPNETCORE_ADLER_HTTPPORT: 80
    volumes:
      - backend_wwwroot:/app/wwwroot
    depends_on:
      - db_backend
    restart: unless-stopped
    extra_hosts:
      - ${_DOMAIN}:host-gateway

  frontend:
    image: ghcr.io/projektadler/2d_3d_adler:latest
    ports:
      - 8087:80
    environment:
      API_URL: "http://${_URL_BACKEND}/api"
    restart: unless-stopped

  phpmyadmin_wsl:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOSTS: db_moodle,db_backend
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${_DB_ROOT_PW}
    restart: unless-stopped
    depends_on:
      - db_backend
      - db_moodle
    ports:
      - 8088:80

volumes:
  moodle_moodle:
    driver: local
  moodle_moodledata:
    driver: local
  db_moodle_data:
    driver: local
  db_backend_data:
    driver: local
  backend_wwwroot:
    driver: local